# Generated by Django 4.0.6 on 2022-07-10 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('u_online_shop', '0004_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='seller_pay',
            new_name='seller_paid',
        ),
    ]
